algolia/docsearch

src/lib/DocSearch.js
src/lib/utils.js
test/utils-test.js

Given a hit returned by the API and a key, will return the highlighted value if one is present, or the default key otherwise. Added some tests to it, and moved it to utils.

test(utils): Add tests for getHighlightedValue

---

src/lib/DocSearch.js
src/lib/utils.js
test/utils-test.js

Same underlying logic than getHighlightedValue, but also add prefix
and suffix ellipsis (…) when we detect that a snippet is truncating
a sentence.

test(utils): Add tests for getSnippettedValue

---

src/lib/DocSearch.js
test/DocSearch-test.js

I had to change some methods to static to be able to tests them
without instantiating a new DocSearch. I also used better `restore`
methods of sinon.js.
I did not manage to correctly test the promise returned by the method
returned by getAutocompleteSource. I would have like to test that when
resolved it correctly call reformatHits on the data as well as call
the callback on the reformated hits but got confused in
spying/stubbing/mocking the promise.

test(getAutocompleteSource): Add tests for source

---

README.md

Small rewording, typos and links.

docs(readme): Small rewording

---

.gitignore
package.json
src/lib/DocSearch.js
src/lib/utils.js
test/DocSearch-test.js
test/fixtures/formatHits.json
test/utils-test.js

The main logic of the library: splitting a set of 5 results into
a neatly ordered array, to be able to display it as two columns in
Hogan.

test(formatHits): Add tests for formatHits

---

src/lib/DocSearch.js
test/DocSearch-test.js

This should let developpers use it in a dev environment.
Fixes #21
cc @maxiloc

fix(appId): Allow passing a custom appId

---

README.md
docs/css/_base.scss
docs/css/_home.scss
docs/css/_syntax-highlighting.scss
docs/documentation.md

- highlight background CSS rules was wrongly configured
- navbar-header text was black
- active links had a default black background
- fixed a few links using references instead of actual links (doesn't
work once extracted to documentation.md)
- use absolute image path

docs(website): a few CSS & README minor fixes

---

src/lib/DocSearch.js

fix(handleSelected): ensure we're calling setVal on the right object

---

src/lib/DocSearch.js
test/DocSearch-test.js

fix(url): Removes concatenation of URL with hash if it contains a hash

---

README.md
src/lib/DocSearch.js
src/lib/templates.js
test/DocSearch-test.js
test/helpers.js

I've added sections about the `algoliaOptions` and `autocompleteOptions` parameters. The rest is simply formatting of the readme as well as fixing some linting issues (line too long, no jsdoc).

docs(options): Add documentation about custom options

---

README.md
scripts/build-docs

Fix by importing all the links of the README inside the `documentation.md` file.
Fixes #65

docs(documentation.md): Fix not working links

---

src/styles/main.scss

In the current version, each row in the left column (display sub categories) are separated with a line, even when two suggestions belong to the same sub-category. 
Removing those, and making the interlines lighter in the right column, improves readability.
Makes it easier for the brain to understand that some items belong to a same sub-category.
Also disabled the mouse hover look'n'feel when hovering the left column.

fix(dropdown): Visually group suggestions together

---

README.md

Ensure the links are correctly interpreted by the documentation website.

Fixed markdown links inside code blocks

---

src/lib/DocSearch.js

Use autocomplete.js's autoselect=true option to select the top
suggestion on <ENTER> even if you don't move the cursor.
Fix #81

fix(autocomplete): auto select top result

---

src/lib/DocSearch.js
test/DocSearch-test.js

While overriding the algoliaOptions, we were losing the default
hitsPerPage query parameters.
Fix #78

fix(algoliaOptions): ensure we keep default options

---

src/lib/utils.js
test/utils-test.js

Consider the key's lowercase form while grouping

---

README.md
scripts/serve

Running `npm run serve` will watch for changes in the source files and
rebuild all `css` and `js` files accordingly in the `dist` folder. It
will also expose the same files on `http://localhost:8080/` (by
default, if port `8080` is already taken it will move to an available
one).
This will let developers use a specific branch/version of docsearch in
their projects. Just open a new tab and run `npm run serve` in the
docsearch repo, and you'll be able to include the scripts from the
running server in your HTML.
As files are automatically regenerated on disk whenever a change is
detected, you can also `require` files by targeting the `dist` folder.

feat(serve): Watch and serve all needed files

---

README.md

The link used to point to the ruby explanations, but it didn’t exist at that id. Since it’s using js, I changed it to point to that point in the js documentation

docs(readme): update link to parameters

---

src/lib/DocSearch.js
test/DocSearch-test.js

This PR makes DocSearch more accessible to screen readers.

feat(a11y): Hide separators to screen readers

---

webpack.dev.config.babel.js

This makes local development easier with local builds of autocomplete.js.
`npm link autocomplete.js` throws an error because of a babel related thing
`npm link autocomplete.js` works

chore(build): Use include instead of exclude in webpack dev build

---

README.md

docsearch is published on npm too, but it's a bit confusing that it's actually published as `docsearch.js`, so this should definitely be put somewhere in the README

docs(readme): add installation instructions on npm

---

src/lib/utils.js

**Summary**
fixed #171 
the given data type of docsearch hits might be conflict with the properties of the native Object, such as the constructor, so we need to do this check.

avoid the native Object's properties

---

README.md

**Summary**
This is a tacit agreement, but imho it should really be stated somewhere explicitly.
**Result**
Now it's explicit. 
cc @pixelastic @ElPicador @s-pace

docs(global): Add section on "powered by Algolia" attribution

---

README.md

svg still is pretty bad for support in GitHub (at least now it works a little bit), but remote images work better
also messaged GitHub support about this
fixes #204

docs(readme): link rawgit logo

---

docs/_data/showcase.yml

react -> standalone website
react native -> link to its site instead of react's site

docs(showcase): update React and React Native links

---

src/lib/DocSearch.js

Let through options passed in `autocompleteOptions.cssClasses` and use `prefix: 'ds'` as default.
Right now, options being are overwritten [on these lines](https://github.com/algolia/docsearch/blob/master/src/lib/DocSearch.js#L76-L78).
Have a good weekend! ☀️

fix(autocompleteOptions): allow cssClasses options

---

README.md
docs/source/assets/stylesheets/_searchbar.scss
docs/source/documentation/2-docsearch-scraper/2-config-options.html.md.erb
docs/source/documentation/3-docsearch-autocomplete/1-customize-autocomplete-styles.html.md.erb
scripts/test-coverage
src/lib/DocSearch.js
src/lib/__tests__/DocSearch-test.js
src/lib/templates.js
src/lib/utils.js
src/styles/_dropdown.scss
src/styles/_searchbox.scss

**Summary**
Fixed few typos
**Result**
Less typos
**Care**
Maybe the typo fix of `isTextOrSubcatoryNonEmpty` can provoke a regression somewhere/somehow ?

doc(site): Fixed typos

---

index.js
src/lib/DocSearch.js
src/lib/__tests__/DocSearch-test.js
src/lib/__tests__/utils-test.js
src/lib/main.js
src/lib/utils.js
src/lib/zepto.js

ESLint was complaining about having trailing .js extensions in imports and suggesting removing them as they are the default.

chore(lint): Remove .js extension from imports

---

docs/package.json
docs/scripts/prepush

The `./docs` subfolder contains a git hook (automatically added through husky) that checks for lint before any push, preventing to push content that doesn't comply with our linting rules.
While this is a good thing, it had the side effect of also trigger on unrelated pushes (when editing the main DocSearch code for example). This happened because we have two nested node projects (DocSearch at the root and the docs in `./docs`), each with their own dependencies. But has husky adds git hooks, even if it is defined in the subfolder, it adds them to the whole repo.
This PR now makes sure the prepush hook call a custom script that double check that changes were actually made in the `./docs` subfolder before running the doc linting.
This will allow us to push updates to DocSearch faster, …

Skip linting the docs when making a change to the root

---

docs/src/run-your-own.md

The `./docsearch docker:build` command cannot be run without
previously installing the python dependencies as those dependencies
are needed to run the CLI.

Update installation instructions

---

docs/src/recomended-configuration.md

I know it's rude to overwrite the PR template but I don't think it applies in this case. Let me know if I need to change anything.

docs(website): fix typo

---

scripts/playground.html
src/lib/__tests__/DocSearch-test.js
src/lib/version.js

I added the missing tests for the ctrl-click and handleSelected.
This keeps backward compatibility for `handleSelected`: people that defined it will still have it honored. The way to do it was to intercept all clicks on the dropdown suggestion when a `handleSelected` with defined, and cancel them through `event.preventDefault()`, in order to allow the custom `handleSelected` to be triggered.
I also downgraded the version (that was bumped by mistake to 3.0) in another PR. The version will be automatically bumped in the release script, so no need to update it here. Especially because we don't want to bump to v3 yet.
Finally, I discovered an issue with the tests. Whenever we called `new DocSearch()` it would create slightly different markup of the dropdown (class names include a suffix of …

Add test that normal click is disable with custom handleSelected

---

package.json

Script was removed in 3c98ea588280f02bae581af2f52b69b3f0b044d0, but
the entry stayed.

Remove `release:beta` entry

---

scripts/playground.html

**Summary**
This removes some redundant code from the recommended HTML snippet. See <https://mathiasbynens.be/notes/html5-levels#type-attributes>.
**Result**
This is valid HTML. `text/javascript` is the default `type` for `<script>` elements per spec, and this is implemented by all browsers.

Omit redundant `type="text/javascript"`

---

docs/src/behavior.md
package.json
scripts/playground.html
src/lib/DocSearch.js
yarn.lock

This updates the underlying autocomplete.js to a version that passes
the selection context (click or keyboard) to the
`autocomplete:selected` event.
With the default `handleSelected`, and in the case of a click, it will
do nothing (as each suggestion already being a `<a href>`, it will
already follow the link), but manually change the location for
keyboard navigation.
When a custom `handleSelected` is set though, default browser clicks
on suggestions are disabled and only `handleSelected` is called. This
is to keep backward compatibility with all the live websites that
might already use `handleSelected`.

feat(ctrl-click): Enable Ctrl-Click on suggestions

---

src/lib/__tests__/DocSearch-test.js

Adding tests for the default `handleSelected`. On any context that is not a click, it should empty the input and change the current page. On a click, it shouldn't do any of those things.

test(handleSelected): Add tests on selectionMethod

---

src/lib/DocSearch.js

**Summary**
https://github.com/algolia/docsearch/issues/555
**Result**
``` js
// Usage of new method
docsearch({
...config,
inputSelector: "#docsearch-input",
dataCallback: data => formatData(data)
...
});
---
const clickObject = {
objectID,
position,
queryID //queryID of inner query, can now retrieve from within DocSearch instance
};
// Algolia Analytics library
aa("click", clickObject); //send the click data to algolia
```

implement query data callback method into src

---

docs/src/inside-the-engine.md

This commit just fixes a set of minor typos in the text, that I found while reading through it. It also makes a small grammar adjustment as well, for greater reading clarity.
**Summary**
**Result**

Fix a set of minor typos in "Inside the Engine -> Ranking Records"

---

docs/src/integrations.md

The current VuePress Algolia link currently goes to a 404 page. This simple PR just fixes the link.

Fixed VuePress Algolia link

---

src/lib/DocSearch.js

**Summary**
#418 
The search input does not have `aria-label`. I have found the underlying cause, it is because we are not passing `ariaLabel` options to autocomplete.js
See https://github.com/algolia/autocomplete.js/#global-options
> `ariaLabel` - An optional string that will populate the aria-label attribute.
My implementation is
- Check autoCompleteOptions for `ariaLabel`
- Otherwise, check original input selector `aria-label`
- Otherwise, use `search input` as aria-label
**Test Plan**
Here is my input
```html
<input
id="search_input_react"
type="search"
placeholder="Search"
aria-label="This is my aria-label from endiliey"
/>
```
**Before**
No aria-label
**After**
aria-label exist

fix: search input a11y issue

---

src/lib/DocSearch.js
src/lib/__tests__/DocSearch-test.js

**Summary**
Attempt to continue work on https://github.com/algolia/docsearch/pull/679
Previously it was reverted because there is no safe getter 😭 
**Result**
aria-label exist

fix: docsearch input should have aria-label (a11y)

---

.circleci/config.yml
package.json
ship.config.js
yarn.lock

**Summary**
This PR updates the usage of `Ship.js` following up its latest update.
A few things to notice are,
1. The latest version of `Ship.js` better supports monorepo.
Before this commit, publishing to NPM was leveraging `lerna exec` which was flaky with `--tag beta` parameter. Now publishing in monorepo is supported by `Ship.js` out-of-box.
2. It used to guide to add "User Key" of Github at CircleCI dashboard,
but since Ship.js@0.5.0, it uses `GITHUB_TOKEN` environment variable to push things to git remote. So there is no need for "User Key" any more.
More info: https://github.com/algolia/shipjs/blob/master/CHANGELOG.md#050-2019-09-08
**Result**
The script names have changed as well:
```bash
yarn release:prepare
```
and
```bash
yarn release:trigger
```

chore: update release script

---

ship.config.js

**Summary**
Some of the internal dependencies used to have "caret" but while I was adding `ship.js`, I accidentally [removed it](https://github.com/algolia/docsearch/commit/38a9c8e8109f5c74cf116a64c777fc06f79fb784#diff-e07e93c2309dadc70fc37e6b22ff2e04L31-L32).
This PR brings it back.

chore: add caret to some dependencies

---

docs/src/_layouts/homepage.pug

**Summary**
The CircleCI logo is incorrectly labelled as "circle.io" - this PR changes the `alt` attribute and caption to `CircleCI`, although leaves the image name as-is.
**Result**
Glide now reads "CircleCI" as it should

Fix circle.io logo caption to CircleCI

---

docs/src/integrations.md

Just fixing a couple of broken links I found in the docs 🙂

Fix broken link to VuePress and Pkgdown integration docs

---

package.json
ship.config.js

**Summary**
This PR updates the version of Ship.js and its configuration file.
`monorepo.readVersionFrom` has been renamed to `monorepo.mainVersionFile`.
And its functionality has changed a little bit, which is we don't need to update the version of `lerna.json` any more.
**Result**
It works the same.

chore: update shipjs version

---

docs/src/_layouts/homepage.pug

fix(homepage): make logo inline block

---

docs/src/config-file.md
docs/src/faq.md
docs/src/required-configuration.md

**Summary**
As above. [Best practice](https://developer.mozilla.org/en-US/docs/Web/HTML/Element) is to portray HTML tags without a forward slash `/`,
especially when the tags aren't self-closing.

Fix HTML element syntax in docs

---

docs/src/integrations.md

**Summary**
I had reached out to the DocSearch support team a month ago about adding Orchid as an official integration once I released the feature. Now that this is released, I am updating the page here with the link to Orchid's DocSearch integration docs.

Add Orchid to supported integrations

---

docs/src/_layouts/homepage.pug

**Summary**
The link used at the moment goes to an older version.
**Result**
View link at: https://getbootstrap.com/docs/4.4/getting-started/introduction/

update Bootstrap docs link to current version

---

docs/src/_layouts/homepage.pug
docs/src/_styles/components.css
docs/src/js/home.js

**Summary**
Fix the following issues noticed on the homepage:
- Logo not centred
- Magnifying glass is not inside the input.
- Make sure to use the latest version of the Bootstrap documentation
**Result**
Logo is centred, logo is well positioned and the demo search is up to date.
_Disclaimer_: This is a hot fix to make since we are going to move on docusaurus v2

fix(homepage): correct small issues

---

packages/docsearch-css/package.json
packages/docsearch-react/package.json

**Summary**
When using `@docsearch/css` with webpack like below:
```
import '@docsearch/css'
```
[`sideEffects: false`](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) would cause webpack to prune all the css.
I have to work around with a hack like this:
```
import styles from '@docsearch/css';
// do something with `styles` to keep it around.
```
**Result**

fix(css): remove `sideEffects` package field

---

packages/docsearch-css/src/button.css
packages/docsearch-react/src/DocSearchButton.tsx

**Summary**
At the moment there is the following HTML issue related to the incorrect use of the `button` tag:
```
Element “div” not allowed as child of element “button” in this context. (Suppressing further errors from this subtree.)
```
I suggest replacing the `button` with a regular `div` element.
**Result**
According to the validator (https://validator.w3.org/nu/#textarea), the error has been fixed.
cc @francoischalifour

fix: use spans inside button tag instead of divs

---

packages/docsearch-react/src/DocSearchButton.tsx

**Summary**
Ability to translate DocSearch placeholder label, a low hanging fruit as it's the most visible one, but there are probably other labels to allow translating (including aria attributes).
This is a pseudo code suggestion, not sure it works yet :) 
You may be happy to know about `ComponentProps` in TS :) 
**Result**

feat: add `translations` prop to search button

---

bundlesize.config.json
packages/docsearch-react/package.json
packages/docsearch-react/src/DocSearchModal.tsx
packages/docsearch-react/src/Results.tsx
packages/docsearch-react/src/ScreenState.tsx
packages/docsearch-react/src/SearchBox.tsx
packages/docsearch-react/src/types/DocSearchHit.ts
packages/docsearch-react/src/useTouchEvents.ts
yarn.lock

**Summary**
We introduced the required `sourceId` prop in https://github.com/algolia/autocomplete/pull/429 and _I assume that_ as the Autocomplete version wasn't pinned, the latest DocSearch version throw an error.
This implementation provides a default `sourceId` to the DocSearch sources.
_Other improvements might be needed but this should fix the current issue._

fix(deps): Update and pin Autocomplete to the latest version

---

bundlesize.config.json
packages/docsearch-react/src/DocSearchModal.tsx
packages/docsearch-react/src/ResultsScreen.tsx
packages/docsearch-react/src/utils/index.ts
packages/docsearch-react/src/utils/removeHighlightTags.ts
packages/docsearch-react/src/utils/unescape.ts

**Summary**
In some cases, the hits returned by the engine can contain escaped characters. We now retrieve the `lvl0` from the `_highlightResults` (which are always unescaped) and remove the highlighting tags.
| before | after |
| --- | --- |
| ![Screenshot 2021-03-31 at 16 55 12](https://user-images.githubusercontent.com/20689156/113164960-e0624c00-9241-11eb-81cb-86cc0732c8de.png) |  ![Screenshot 2021-03-31 at 16 59 27](https://user-images.githubusercontent.com/20689156/113165744-76967200-9242-11eb-8edf-d2a9b9a4c7b1.png)|

fix(results): unescaped lvl0

---

packages/docsearch-react/src/DocSearchModal.tsx
packages/docsearch-react/src/ResultsScreen.tsx
packages/docsearch-react/src/utils/removeHighlightTags.ts

**Summary**
In https://github.com/algolia/docsearch/pull/1001, we introduced a new internal method to escape the  `hierarachy.lvl0` value from `_highlightResult`. When the hit is "linked" to his parent (image below), `_highlightResult` gets replaced by `__docsearch_parent` (which contains the actual hit).

fix(escapedResults): `_highlightResult` is undefined

---

packages/docsearch-react/src/DocSearchModal.tsx

**Summary**
We now use the multi-queries `search` method from the client which allows the user to override the method from `transformSearchClient`.
**Result**
The user can now override the `search` method, to debounce the search for example.
**Example**
[sandbox](https://codesandbox.io/s/docsearch-v3-debounced-search-gnx87)
**Issues**
- Fixes https://github.com/algolia/docsearch/issues/1018
- https://github.com/facebook/docusaurus/issues/5174

refactor(searchClient): use client `search` method

---

packages/docsearch-css/src/button.css
packages/docsearch-react/src/DocSearchButton.tsx

There's a flash of unstyled content regarding the search box:
https://user-images.githubusercontent.com/1091472/125940962-202531fe-58aa-40f5-af9c-fc775eb7c9bf.mov
You can check it on https://docsearch.algolia.com/
Setting a width would eliminate the problem, you can check it on https://webpack.js.org/ for how it looks.

fix: eliminate keyboard shortcuts UI flash

---

packages/docsearch-css/src/button.css
packages/docsearch-react/src/DocSearchButton.tsx

_Follow up of https://github.com/algolia/docsearch/pull/1021_
**Summary**
This PR prevent the UI flash for server-side rendered websites. Since [the `key` value](https://github.com/algolia/docsearch/blob/f38276308a4e0ff140e4c1d4db1beced4f610068/packages/docsearch-react/src/DocSearchButton.tsx#L31-L33) is `null`, the `keys` container isn't rendered and therefore causes a UI flash.
**Result**
The condition is now a level below (on the `key`s), and we've added a fixed `width` to the container.
**Preview**
https://user-images.githubusercontent.com/20689156/126791441-7ef26e5f-3b5d-4002-aee3-9fb627634680.mov
**Related**
- https://github.com/webpack/webpack.js.org/pull/5224
- https://github.com/facebook/docusaurus/pull/5214

fix(button): prevent container keys ui flash

---

.circleci/config.yml

**Summary**
The CI was failing when trying to lint packages from the monorepo

fix(ci): update config file

---

packages/docsearch-js/rollup.config.js
packages/docsearch-react/rollup.config.js

**Summary**
With bare minimal HTML implementation, it is not possible to use the UMD build without manually providing the `process.env.NODE_ENV` variable.
See https://github.com/algolia/docsearch/issues/1046 for more details
**Result**
This PR updates the rollup config to replaces occurrences of `process.env.NODE_ENV` by `"production"`, since we only provide an UMD production file.
Fixes https://github.com/algolia/docsearch/issues/1046

fix(build): remove occurences of `process` in UMD build

---

packages/docsearch-react/src/DocSearch.tsx

**Summary**
`initialQuery` wasn't passed from the props to the state, which made it unusable.
see [sandbox](https://codesandbox.io/s/hopeful-fast-fjdof?file=/src/App.js)
**Result**
Search input is initialized with `initialQuery`
see [sandbox](https://codesandbox.io/s/festive-sara-7o8nf)
Related issue: https://github.com/algolia/docsearch/issues/1050

fix(v3): pass `initialQuery`

---

.circleci/config.yml

**Summary**
Fixes Circle CI docker image issue
See https://circleci.com/developer/images/image/cimg/node for more informations
TLDR: `This image is designed to supercede the legacy CircleCI Node.js image, circleci/node.`

fix(ci): update docker image

---

packages/website/docs/DocSearch-v3.mdx
packages/website/docs/styling.md

**Summary**
The `Getting started` section of DocSearch v3 was missing the CSS import

docs(v3): add missing CSS import

---

packages/website/docs/DocSearch-v3.mdx

- Fix `react` script link
- Mention `preconnect` usage in `installation`

docs(v3): fix `react` script link, mention `preconnect` in `installation`

---

packages/docsearch-react/src/DocSearch.tsx

`searchParameters` were not typed

fix(DocSearchProps): type `searchParameters`

---

packages/docsearch-react/src/AlgoliaLogo.tsx

Due to `noreferrer`, the campaign was always empty when clicking the Algolia logo.
We now inline parameters to prevent this issue.

fix(logo): empty utm campaign

---

packages/website/docs/DocSearch-v3.mdx
packages/website/docs/migrating-from-legacy.mdx
packages/website/docs/record-extractor.md
packages/website/docs/required-configuration.mdx
packages/website/docs/templates.mdx

This PR documents the new `aggregateContent` option available on the crawler.
This option allows users to reduce the number of records outputted by the crawler by aggregating all the records of type `content` in a single record.

docs: document `aggregateContent`, make API ref clearer

---

packages/docsearch-react/src/DocSearchButton.tsx
packages/docsearch-react/src/Footer.tsx

Replaced span tag to [kbd](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd).

fix(button): use kbd instead of span

---

packages/website/docs/api.mdx

Closes #1368 
Documents `resultsFooterComponent`, which was added in https://github.com/algolia/docsearch/commit/9eaf18a81ffff04b7fb8d8389463b56d823f7e9d.

docs: document resultsFooterComponent

---

packages/website/docs/api.mdx
packages/website/docs/record-extractor.md

Documents the new `recordVersion` option to reduce the record size output from the Crawler.

docs: document `recordVersion`

---

packages/docsearch-react/package.json
yarn.lock

Issue: https://github.com/facebook/docusaurus/runs/7027839561?check_suite_focus=true
PR: https://github.com/facebook/docusaurus/pull/7666
`@algolia/autocomplete-preset-algolia` is a type dep for `@algolia/autocomplete-core`, which make type checking throw when performing lib check.
This adds an unmeet `@algolia/client-search` peer dependency warning but should be fixed at the autocomplete level.

chore(deps): bump and fix `autocomplete` deps

---

packages/docsearch-css/src/button.css
packages/docsearch-css/src/modal.css
packages/docsearch-react/src/DocSearchModal.tsx

768px has been much more common for many years (since 2010), and other major CSS frameworks have used 768px as the breakpoint for years.
Closes #1444
- PR for css: #1447
Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)

feat(styles): set medium breakpoint to standarized value

---

.circleci/config.yml
.github/ISSUE_TEMPLATE/Bug_report.md
.github/workflows/renovate.yml
CONTRIBUTING.md
README.md
packages/website/docs/api.mdx
packages/website/docusaurus.config.js

https://algolia.atlassian.net/browse/CRAW-2419
closes https://github.com/algolia/docsearch/issues/1448
I think it's time, we can rename `next` to `main` :D

chore: rename `next` branch to `main`

---

packages/website/docs/templates.mdx

https://algolia.atlassian.net/browse/CRAW-2430
Adds the `maxDepth` parameter to the recommended templates.

docs: add `maxDepth` to templates

---

packages/website/docs/record-extractor.md

This PR adds an `of` to the heading.

docs: typo in heading

---

netlify.toml

I need to deploy the new docs but somehow the netlify cache hits when the preview is deployed on the PR and then needs to be deployed on main 🤔

chore: remove ignore build

---

packages/website/docusaurus.config.js

https://algolia.atlassian.net/browse/CRAW-2453
Logo is a big too big on the docs

docs: reduce Algolia logo size

---

packages/docsearch-css/src/modal.css

Closes https://github.com/algolia/docsearch/issues/1731
Users of DocSearch can always customize as needed.

fix(modal): enable outline for focus state

---

packages/docsearch-react/src/DocSearch.tsx

`({ query: string }) => string;` was being interpreted as a prop rename, which doesn't make sense in the context of an interface, so I've corrected it to what I assume was the intended outcome where `query` is of type `string`, rather than being inferred as `any`.
NOTE: Technically this is a breaking change as `query` was being inferred with type `any`, so consumers that were using it as such may need to change their code. On the other hand, I doubt many consumers are using this value as if it were anything _but_ a `string`, so IMO a patch fix is also valid in this case. I'll leave this decision to the maintainers.

fix: Correctly type `getMissingResultsUrl` query as `string`

---

packages/website/docs/record-extractor.md

This PR updates the type of `lvl0` in the docs. Fix #1856.

docs: update type of lvl0

---

packages/docsearch-react/src/DocSearchModal.tsx
packages/docsearch-react/src/Results.tsx
packages/docsearch-react/src/ScreenState.tsx
packages/docsearch-react/src/utils/index.ts
packages/docsearch-react/src/utils/isModifierEvent.ts

This PR checks for presence of `shiftKey`, `ctrlKey` or `metaKey` when clicking the result so users can open multiple search results without re-opening the search modal.

Fix: Prevent calling `onClose()` when `shiftKey`, `ctrlKey` or `metaKey` is pressed

---

packages/docsearch-react/src/DocSearch.tsx
packages/docsearch-react/src/DocSearchModal.tsx
packages/docsearch-react/src/utils/groupBy.ts

This PR implements the `maxResultsPerGroup` prop, allowing us to customize the number of displayed results in a group (previously hardcoded to 5, changed to 7 on the example below).
```html
<DocSearch ... maxResultsPerGroup="7" />
```

feat: implement `maxResultsPerGroup` prop

---

bundlesize.config.json
examples/demo/src/App.js
package.json
packages/docsearch-react/package.json
packages/docsearch-react/src/DocSearch.tsx
packages/docsearch-react/src/DocSearchModal.tsx
packages/docsearch-react/src/types/DocSearchHit.ts
packages/website/docs/DocSearch-v3.mdx
yarn.lock

This PR updates the version of `autocomplete-core` that we are using to allow for sending events within DocSearch.
Allowing for events to be sent will unlock more features in the long run for DocSearch and can help give insight into how users are using DocSearch on each site.

feat(api): allow insights options to be forwarded to Autocomplete

---

packages/website/docs/DocSearch-v3.mdx

Updates our code snippet of using the `insights` option within the JS package.
Pointed out by: https://github.com/algolia/docsearch/issues/1045#issuecomment-1583044970

(chore): Updates the documentation for insights in JS

---

packages/website/docs/templates.mdx

We are going to release Docusaurus v3 this summer and need a place to link to the new v3 config.
It is just a copy for v2 for now, but I think it's preferable to do the duplication in case the configs diverge in the future: we don't want to impact v2 users if we do changes only in Docusaurus v3

docs: add docusaurus-v3 entry

---

packages/website/docs/DocSearch-v3.mdx

This PR fixes tiny typo in [Installation](https://docsearch.algolia.com/docs/DocSearch-v3) section for `JavaScript`
```diff
- manger
+ manager
```

docs(v3): fix typo

---

packages/website/versioned_docs/version-legacy/config-file.md

This section of the doc made it seem like a URL object is required to use RegEx, but it works fine in just a string array.

Clarify RegEx requirements

---

bundlesize.config.json
packages/docsearch-react/package.json
packages/docsearch-react/src/DocSearchModal.tsx
yarn.lock

Addressing a comment from Docusaurus on one of their deps update [PRs](https://github.com/facebook/docusaurus/pull/9148#issuecomment-1637047133).
This PR updates the `algoliasearch` package version and also adds the `search-client` peer-dependency that is now needed after recent `insights` updates.

chore: Prepare for Docusaurus update

---

bundlesize.config.json
packages/docsearch-css/src/_variables.css
packages/docsearch-css/src/button.css
packages/docsearch-react/src/DocSearchButton.tsx

Add this subtle effect that responds to keypress on <kbd>Meta</kbd>/<kbd>Ctrl</kbd> and <kbd>K</kbd>.
https://github.com/algolia/docsearch/assets/8225666/c35e4c9f-7295-44d4-b258-51250ea4c0e7
https://github.com/algolia/docsearch/assets/8225666/00299419-9bf2-46e1-9f49-105e9d32089c

feat: add keypress effect to DocSearchButton

---

packages/website/docs/api.mdx

Adds a missing backtick and fixes the formatting.

docs: add missing backtick to `placeholder` default example

---

bundlesize.config.json
packages/docsearch-css/src/modal.css
packages/docsearch-react/src/DocSearchButton.tsx
packages/docsearch-react/src/SearchBox.tsx
packages/docsearch-react/src/__tests__/api.test.tsx
packages/docsearch-react/src/icons/SearchIcon.tsx
packages/website/docs/api.mdx

There are 2 main changes in this PR:
- **Allows passing `aria-hidden` to the SearchIcon** so it can be hidden to assistive tech users. The unlabelled SVG can be accessed by screenreaders and can also get caught by automated accessibility audits. Since it's decorative, we can safely hide it with `aria-hidden="true"` in `<SearchBox />` and `<SearchButton />`
- **Adds an accessible label, `searchInputLabel`, to the search form's input.** Currently the `<input />` is associated with a `<label>` that does not have an accessible label, only an unlabelled SVG as a child element. This PR adds accessibly hidden text within the `<label>`. I opted to use visually hidden text (using CSS to hide the text but still make it available for assistive tech users) for the label text because it's generally a …

fix(docsearch-react): add aria-hidden to SearchIcon and add accessible label to SearchBox input

---

packages/website/docs/integrations.md

Hey, I found link to **vitepress** is referring to **vuepress**.
- Fixed by adding correct URL for vitepress docs.

docs: fix link to vitepress

---

packages/website/docs/crawler.mdx

docs: Users are unfortunately deleting their crawlers which result in broken processes. We will fix this in the longer term but in the shorter term putting in these FAQs.

docs: update crawler.mdx

---

packages/website/src/components/ApplyForm.js

The "Thank you!" is misleading in this case because people think they've submitted the form but haven't because it was a duplicate. Made a change to make the situation more clear.

fix(apply form): Update ApplyForm.js

---

packages/website/docs/DocSearch-program.md
packages/website/docs/crawler.mdx
packages/website/docs/required-configuration.mdx
packages/website/versioned_docs/version-legacy/faq.md
packages/website/versioned_docs/version-legacy/how-do-we-build-an-index.mdx
packages/website/versioned_docs/version-legacy/integrations.md
packages/website/versioned_docs/version-legacy/required-configuration.md

This is a change by support (this email goes to support and automatically creates a ticket), support is no longer accepting ticket creation via email. Replacing with links to Discord or proper support site. More info can be found at https://algolia.atlassian.net/browse/ZA-268

fix(email): docsearch@algolia.com is being retired

---

examples/demo/src/App.js
packages/docsearch-react/src/utils/removeHighlightTags.ts

https://algolia.atlassian.net/browse/DI-2986
There seems to be a bug on the indexing side which impacts some DocSearch users. This bug has been reported to me by @rickhanlonii and fixed in https://github.com/reactjs/react.dev/pull/7183 temporarily, but we can globally mitigate this issue which also impacts other DocSearch users such as https://vuejs.org/, https://tailwindcss.com/
We now default to the non highlighted lvl0 in case the highlightResult value is not present
You can try this fix by running `yarn playground:start` on `main` and this branch:
- On main (or just https://vuejs.org/), no section appears (cf screenshot 1
- On this branch (cf screenshot 2)

fix(hits): default to hierarchy lvl0 if highlights present

---

packages/docsearch-css/package.json
packages/docsearch-js/package.json
packages/docsearch-react/package.json
ship.config.js

`yarn publish` doesn't exists anymore

fix: use npm for release

---

packages/docsearch-css/src/_variables.css
packages/docsearch-css/src/button.css
packages/docsearch-css/src/modal.css
packages/website/src/css/custom.css
packages/website/src/css/fragments.css

Hello, I've improved the readability of `_variables.css`.
The code had a different style of formatting compared to the rest, which I believe reduced readability for others.

refactor: improve readability of `_variables.css`

---

packages/docsearch-react/package.json
packages/docsearch-react/src/DocSearch.tsx
yarn.lock

Offer a more compatible type to avoid breaking changes.

fix: use SearchParamsObject for searchParameters

---

packages/docsearch-css/package.json
packages/docsearch-js/package.json
packages/docsearch-react/package.json

Hello,  
I’ve added the `repository.directory` property to `package.json`.  
This property is mentioned in the [npm documentation](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository) and can be useful for maintaining a monorepo.  
It helps tools like npm and GitHub identify the specific directory within the repository where the package is located, which is especially beneficial in monorepo setups.

chore: add `repository.directory` property to `package.json`

---

packages/website/src/components/ApplyForm.js

A user asked a question about this text. I felt like it was misleading since you can apply again if you already have a docsearch application. Users do this when they need to cover another domain and want a separate index.
What we won't accept is an application that covers a domain that has previously been approved. In that scenario, the submitted form has an obvious message that its a duplicate domain.

docs: update ApplyForm.js

---

packages/docsearch-css/src/button.css
packages/docsearch-css/src/modal.css
packages/website/src/css/custom.css

closes https://github.com/algolia/docsearch/issues/2414
> LibSass and older versions of Dart Sass and Ruby Sass don’t support media queries with features written in a [range context](https://www.w3.org/TR/mediaqueries-4/#mq-range-context). They do support other standard media queries.
https://www.w3.org/TR/mediaqueries-4/#mq-range-context
https://sass-lang.com/documentation/at-rules/css/#media

fix(css): older sass supported syntax

---

packages/docsearch-css/src/button.css

Enhance button interaction by adding transition effects for a smoother user experience.
https://github.com/user-attachments/assets/5495047b-749d-4d84-bc6f-e3fa4caf9054

Add transition effects to input buttons for improved interaction

---

cypress/e2e/search/actions.spec.ts
packages/docsearch-react/package.json
packages/docsearch-react/src/Results.tsx
yarn.lock

There are two distinct a11y bugs which are related to each-other:
1. The main input `.DocSearch-Input` contains `aria-controls="docsearch-recentSearches-list docsearch-favoriteSearches-list"` which is not compliant because the `recentSearches` or `favoriteSearches` elements do not exist all the time in the DOM. Only if existing favorites or recent searches they should be added - see https://github.com/microsoft/playwright.dev/issues/1628. The fix for this is in https://github.com/algolia/autocomplete/pull/1302. 
2. When there is a _Recent_ and a _Favourite_ results list is shown, they share the same underlying `id="docsearch-list"`. This PR addresses that and adds a test for both issues.
**Investigation**
This seems to render the search list here: …

fix(a11y): have unique ids for favorite/recent lists

---

packages/docsearch-css/package.json
packages/docsearch-js/package.json
packages/docsearch-react/package.json
yarn.lock

Replaced the usage of `yarn watch` with `nodemon` in three packages.
We're making this change due to performance issues observed with the native `yarn watch` command. It tends to be less reliable and slower in larger projects or when multiple watchers are involved.
Switching to `nodemon` improves:
- File change detection
- Restart times
- Overall developer experience
- Better performance during development
- More reliable and consistent watch behavior
- Easier to customize and debug

chore(deps): replace yarn watch with nodemon

---

packages/docsearch-css/src/modal.css

Fixes #2243 
- **fix(docsearch-css): use correct size and position**
- **fix(docksearch-css): prevent mobile body scrolling**
Makes the modal sized correctly and prevents background scroll on mobile (the trade-off of no-background-scroll is that you get scrolled to top of page, but this is only necessary on mobile).
---
-webkit-fill-available is no longer even an option:
- https://caniuse.com/intrinsic-width
- https://developer.mozilla.org/en-US/docs/Web/CSS/WebKit_Extensions
`max-content` is close equivalent, but it is not what you want when you actually want the thing to take up the full viewport.

fix: size and background scroll fixes

---

bundlesize.config.json
cypress/e2e/search.spec.ts
examples/demo-askai/src/App.tsx
packages/docsearch-css/src/_variables.css
packages/docsearch-css/src/modal.css
packages/docsearch-js/package.json
packages/docsearch-react/src/AggregatedSearchBlock.tsx
packages/docsearch-react/src/AlgoliaLogo.tsx
packages/docsearch-react/src/AskAiScreen.tsx
packages/docsearch-react/src/DocSearchButton.tsx
packages/docsearch-react/src/DocSearchModal.tsx
packages/docsearch-react/src/MemoizedMarkdown.tsx
packages/docsearch-react/src/Results.tsx
packages/docsearch-react/src/ScreenState.tsx
packages/docsearch-react/src/SearchBox.tsx
packages/docsearch-react/src/StartScreen.tsx
packages/docsearch-react/src/__tests__/api.test.tsx
packages/docsearch-react/src/__tests__/askai.test.tsx
packages/docsearch-react/src/askai.ts
packages/docsearch-react/src/constants.ts
packages/docsearch-react/src/icons/AlertIcon.tsx
packages/docsearch-react/src/icons/SparklesIcon.tsx
packages/docsearch-react/src/icons/index.ts
packages/docsearch-react/src/stored-searches.ts
packages/docsearch-react/src/token.ts
packages/docsearch-react/src/types/StoredDocSearchHit.ts
packages/docsearch-react/src/utils/groupConsecutiveToolResults.ts
packages/docsearch-react/src/utils/index.ts
packages/docsearch-react/src/utils/scrollTo.ts

**What & Why**
DocSearch v4’s “Ask AI” beta is getting a round of polish so that we can start onboarding external users.  
This PR tightens the UX, improves visual consistency and, most importantly, adds the bearer-token flow required by the new Ask AI API.
---
* Ask AI screen  
* disclaimer is now shown at the top, smaller and left-aligned (less noise, keeps context visible)  
* error banner redesigned with an alert icon, red tint and better spacing  
* “copy / like / dislike” action bar added to every answer (tool-tips translated)  
* search tool calls are clearer (`🔍  Searched documentation for "<query>"`)  
* highlighted query in Ask-AI-button now uses `<mark>` to match Algolia highlighting
* Dropdown behaviour  
* when the query is empty AND there are no stored/favourite searches we …

fix(v4): ask ai updates

---

packages/docsearch-js/package.json
packages/docsearch-js/rollup.config.js

Since the js package is shipped as a bundle, there's no need to bundle the react dependency in it. 
We changed it to a dev dependency. It should help reduce the bundle size and fix a few issues with installing the dependency in non-react frameworks.
see https://github.com/vuejs/vitepress/issues/472 for more context on this fix.

chore(deps): change react to dev deps on js package

---

packages/docsearch-js/rollup.config.js

JS package fails at runtime due to lack in dependency,
We are undoing this change for now.
https://github.com/vuejs/vitepress/issues/472
We will further investigate on this issue.

fix: revert to internal package

---

package.json
packages/docsearch-js/package.json
packages/docsearch-js/rollup.config.js
packages/docsearch-js/src/docsearch.tsx
packages/docsearch-react/package.json
packages/docsearch-react/rollup.config.js
packages/docsearch-react/src/DocSearch.tsx
packages/docsearch-react/src/__tests__/api.test.tsx
packages/website/docs/api.mdx
rollup.base.config.js
yarn.lock

- Exposing `portalContainer` to help select on what node the react component portals to.
- Bundling relevant external types in the JS component.
Fixes: #2695 and #2693

feat: expose `portalContainer` and bundle types in js esm builds

---

examples/demo-react/src/App.tsx
examples/demo-react/src/examples/multi-index.tsx
packages/docsearch-react/src/DocSearch.tsx
packages/docsearch-react/src/DocSearchModal.tsx
packages/docsearch-react/src/__tests__/api.test.tsx
packages/website/docs/api.mdx
packages/website/docusaurus.config.mjs

Adds support for multi-index search during keyword search. This does not impact AskAI in any way.
- Add new `indices` property to accept a list of indexes for search
- Add deprecation messaging to `indexName` and `searchParameters` properties
- Manage backwards compatibility for now until `indexName` and `searchParameters` are fully removed
- Add another example of multi-index search
- Adds documentation for `indices` and deprecation warnings for `indexName` and `searchParameters`
- Enables `respectPrefersColorScheme` within Docusaurus config

feat(v4): Add support for multi-index search

---

packages/docsearch-react/src/DocSearch.tsx
packages/docsearch-react/src/DocSearchModal.tsx
packages/docsearch-react/src/__tests__/api.test.tsx

Fixes a TS/runtime issue when rendering the `<DocSearchModal />` directly after the recent `indexName` deprecation. This moves the fallback safeguard within the modal itself to allow the index props to be passed directly to it.

fix(modal): Fixes issue with index typings on DocSearchModal

---

packages/docsearch-css/src/_variables.css
packages/docsearch-css/src/modal.css
packages/docsearch-react/src/DocSearchModal.tsx
packages/docsearch-react/src/Results.tsx

• Improves modal responsiveness by introducing dynamic viewport height for the dropdown container while maintaining the existing max-height constraint
• Fixes issue where starting a new conversation wasn't properly clearing previous messages by moving the message clearing logic to the question selection handler
• Refines typography and spacing across the Ask AI interface for better readability (adjusted font sizes, line heights, and margins)
• Fixes HTML entity encoding in collection titles by properly decoding them before display

feat: Modal UI/UX fixes and updates
