dev/docsearch-styling.css, dev/index.html, src/styles/_variables.scss, src/styles/main.scss
=> feat(styling): Set grayscale as default, add styling as external file

.travis.yml, CONTRIBUTING.md, README.md, docs/_config.yml, docs/index.haml, npm-shrinkwrap.json, package.json, scripts/build-css, scripts/build-js, scripts/bump-package-version.js, scripts/docs/gh-pages.js, scripts/docs/update-website, scripts/finish-release, scripts/gh-pages, scripts/release, scripts/release-beta, scripts/test-ci, scripts/validate-commit-msgs, scripts/validate-pr-done-on-develop, src/lib/DocSearch.js, src/lib/main.js, src/lib/version.js
+ add specific algolia agent to the js client
+ add npm run release, npm run release:beta
+ add CONTRIBUTING guide
+ finish rename to /docsearch
=> chore(release): add release process

src/styles/_variables.scss, src/styles/main.scss
=> Lighter default colors

dev/docsearch-styling.css, src/lib/DocSearch.js, src/lib/templates.js, src/styles/main.scss
=> fix(css): Renaming all `ads-` prefix to `algolia-docsearch-`

README.md, dev/app.js, docs/documentation.md, src/lib/main.js
=> chore(naming): use `docsearch` everywhere

src/lib/templates.js, src/styles/main.scss
=> fix(isSubCategoryHeader): ensure we hide the content of the left column if this flag is not set

docs/_config.yml, docs/_layouts/default.html
This PR only adds the needed elements to the markup. We still need to fill them with relevant values in `_config.yml`.
See #25
=> docs(opengraph): Add opengraph meta

docs/Gemfile, docs/Gemfile.lock, docs/_includes/join-form.haml, docs/_plugins/haml.rb, docs/css/_home.scss, docs/index.haml, docs/js/home.js
Move the forms to a partial (had a hard time with HAML-based partials...)
Small box-shadow if not specified
Add a "I'm the owner of that website" checkbox
=> feat(website): ensure the inputs are mandatory

docs/_includes/header.html, docs/_includes/searchbar.html, docs/_layouts/default.html, docs/css/_searchbar.scss, docs/css/main.scss
=> add docsearch

docs/css/_docsearch.scss
=> docs(search): improved header highlighting + fixed padding

npm-shrinkwrap.json, package.json
This includes latest autocomplete.js to handle multiple inputs binding.
Ref #74 & #80
=> chore(deps): upgraded deps

docs/index.haml
Signed-off-by: Vishal Rana <vr@labstack.com>
=> Fixed link for echo

docs/_includes/header.html, src/lib/templates.js
Minor copy update in the DocSearch site search and for the default placeholder on participating sites.
=> s/Search in the doc/Search the docs

docs/_includes/footer.html
Replaced the utm that was referencing places_website
=> docs(places): Replace utm referencing places

README.md
Update CDN from README
cf algolia/docsearch#207
=> docs(update CDN) cf algolia/docsearch#207

docs/app_data/showcase.yml
=> Fix typo in Fastlane

README.md, docs/source/assets/stylesheets/_searchbar.scss, docs/source/documentation/2-docsearch-scraper/2-config-options.html.md.erb, docs/source/documentation/3-docsearch-autocomplete/1-customize-autocomplete-styles.html.md.erb, scripts/test-coverage, src/lib/DocSearch.js, src/lib/__tests__/DocSearch-test.js, src/lib/templates.js, src/lib/utils.js, src/styles/_dropdown.scss, src/styles/_searchbox.scss
=> Revert "doc(site): Fixed typos"

README.md, docs/source/assets/stylesheets/_searchbar.scss, docs/source/documentation/2-docsearch-scraper/2-config-options.html.md.erb, docs/source/documentation/3-docsearch-autocomplete/1-customize-autocomplete-styles.html.md.erb, scripts/test-coverage, src/lib/DocSearch.js, src/lib/__tests__/DocSearch-test.js, src/lib/templates.js, src/lib/utils.js, src/styles/_dropdown.scss, src/styles/_searchbox.scss
Reverts algolia/docsearch#278
Apply algolia/docsearch#277
Should work know. Thank you @pborreli
=> Revert "Revert "doc(site): Fixed typos""

docs/source/assets/javascripts/main.js, docs/source/index.html.haml, docs/source/partials/join-form.haml
**Make the docsearch form GDPR compliant**
Needed to be 100% GDPR compliant. 
**Result**
Check the code
=> Make the form GDPR ready

docs/app_data/showcase.yml
**Summary**
_fastlane_ is always written in lowercase 😃
**Result**
=> Fix incorrect text case for fastlane

docs/source/documentation/4-docsearch-FAQ/3-does-my-project-qualify.html.md.erb
=> Fix a typo in the project qualification docs

docs/config.json
=> fixing extra link

docs/src/js/home.js
=> restraining the bootstrap demo to the latest version

src/styles/_dropdown.scss
There was some conflict markers left in the SCSS file.
=> Remove git markers in file

CONTRIBUTING.md, package.json
=> Remove postinstall

docs/package.json, docs/scripts/netlify-deploy-preview, docs/yarn.lock, package.json, yarn.lock
More info: https://github.com/dominictarr/event-stream/issues/116
=> fix(security): Fix dependencies to avoid infected event-stream

docs/src/behavior.md, docs/src/config-file.md, docs/src/run-your-own.md
**Summary**
see algolia/docsearch-scraper#419
**Result**
=> update as algolia/docsearch-scraper#419

docs/src/who-can-apply.md
**Summary**
`.HTML` leads to a 404 error in Chrome:
**Result**
=> fix 404 page caused by .HTML

docs/src/faq.md
**Summary**
📖 Just a simple one-character change to fix a typo in the docs.
**Result**
✏️ Analyti~~u~~cs → Analytics
=> Fix Analytics typo

README.md, package.json, yarn.lock
don't merge, still need to remove the tool itself too I think (will do if approved)
**Summary**
**Result**
=> docs(readme): remove ToC

docs/src/config-file.md
Documentation for https://github.com/algolia/docsearch-scraper/issues/425.
=> document the UPDATE_NB_HITS configuration variable

docs/src/config-file.md
Objectives:
- using feedback from algolia/docsearch-configs#795
- better hierarchy
🙏 @codeharmonics for a quick proofreading
=> doc(content) Updating configuration sectiion

docs/src/_layouts/homepage.pug
Noticed a small typo while going through the site :)
=> fix typo strutured -> structured

docs/src/faq.md, docs/src/run-your-own.md, docs/src/styling.md
- Add faq about how many records are created
- Update the run on your own section to avoid any confusion
- Remove wrong part of the attribution policy
=> Doc: update content

src/lib/DocSearch.js
=> Revert "fix: search input a11y issue"

docs/src/_layouts/homepage.pug
**Summary**
[The website](https://community.algolia.com/docsearch/) still says the copyright is "2015-2018" all the way at the bottom.
**Result**
=> Update year of copyright

docs/src/_layouts/homepage.pug
**Summary**
I noticed that the PayPal logo tooltip on the homepage had a typo, and this pr fixes it!
**Result**
`Paypal` ➡️`PayPal`
=> Fix typo on docs homepage

docs/src/config-file.md
Documentation for https://github.com/algolia/docsearch-scraper/issues/426
=> document the INDEX_NAME_TMP configuration variable

docs/src/inside-the-engine.md
**Summary**
I have added an `e` to the end of `scrap` to make it say `scrape`, which I what I believe it should be.
**Result**
It now says `scrape` instead of `scrap`.
=> The word you are wanting is 'scrape'

CHANGELOG.md, examples/vanilla/package.json, lerna.json, packages/docsearch-core/package.json, packages/docsearch-core/src/version.ts, packages/docsearch-renderer-downshift/package.json, packages/docsearch-theme-light/package.json, packages/docsearch-types/package.json, packages/docsearch/package.json
_This was generated by [ShipJS](https://github.com/algolia/shipjs/)._
This PR prepares the v3 beta release.
=> chore: release v3.0.0-beta.0

docs/src/behavior.md, docs/src/config-file.md, docs/src/crawler-overview.md, docs/src/run-your-own.md
Solves misleading documentation on transformData
Solves textlint issue
=> Doc: enhance transformData description

docs/src/behavior.md
resolves #588 and avoid wrong comment
=> Update handleSelect documentation

docs/src/dropdown.md, docs/src/faq.md
=> Doc: Add details

docs/README.md, docs/src/config-file.md, docs/src/css-helper.md, docs/src/dropdown.md, docs/src/faq.md, docs/src/how-do-we-build-an-index.md, docs/src/how-does-it-work.md, docs/src/inside-the-engine.md, docs/src/integrations.md, docs/src/required-configuration.md, docs/src/run-your-own.md, docs/src/styling.md, docs/src/tips.md, docs/src/what-is-docsearch.md, docs/src/who-can-apply.md
Fix most of the warnings of textlint => Better content
=> Doc: Remove warnings of textlint

docs/config.json
=> Fix wrong menu link

docsearch/src/pages/applyComponent.js
=> style(form)

docs/src/tips.md
Simple typo fix: diretly --> directly
**Summary**
Simple typo fix. Let's make sure spelling is correct :smile_cat:
=> Fix typo: diretly --> directly

docs/src/config-file.md, docs/src/faq.md, docs/src/inside-the-engine.md
=> doc: remove typo and clumsy wording

docsearch/src/pages/demo-projects.json, docsearch/src/pages/index.js, docsearch/src/pages/showcase-projects.json
The demo and showcase projects were hardcoded in the page. This PR generates them from a data file.
=> feat(projects): generate demo and showcase projects grid

src/styles/_dropdown.scss
Minor tweaks: remove duplicate properties
=> Remove duplicate properties

docs/src/_includes/header.pug
Those where sending to the old community websites (only React had a redirect to the new documentation).
See ya!
**Summary**
**Result**
=> docs(header): update InstantSearch* links to new docs

src/lib/DocSearch.js
**Summary**
I noticed this typo while I was working on a fork of this project. I could just ignore this but I can't stop thinking about the typo 😮 .
**Result**
This fix should work fine because the parameter `layout` will be ignored unless its value is `"simple"` anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algolia/docsearch/890)
=> Typo collumns => columns

.github/ISSUE_TEMPLATE/docsearch_ui.md, README.md
Follow algolia/docsearch-configs#1730
=> fix: use correct url

yarn.lock
This PR fixes the build error:
```sh
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["object-assign@latest"] is trying to unpack in the same destination "/Users/sylvain.pace/Library/Caches/Yarn/v6/npm-object-assign-4.1.1-2109adc7965887cfc05cbbd442cac8bfbb360863-integrity/node_modules/object-assign" as pattern ["object-assign@^4.1.0","object-assign@^4.1.0","object-assign@^4.0.1","object-assign@^4.0.1","object-assign@^4","object-assign@^4.1.1","object-assign@^4.1.1"]. This could result in non-deterministic behavior, skipping.
error An unexpected error occurred: "https://registry.yarnpkg.com/es-abstract/-/es-abstract-1.14.0.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in …
```
=> fix(deps): update failling yarn.lock

package.json, yarn.lock
=> fix(website): add workspace `nohoist` for Docusaurus

packages/website/docs/migrating-from-legacy.mdx, packages/website/docs/record-extractor.md, packages/website/package.json, yarn.lock
**Summary**
- Add and clarify questions in the Migration FAQ
- Add an example on how to use `pageRank`
- Upgrade Docusaurus version (closes https://github.com/algolia/docsearch/pull/1114)
=> docs(website): add FAQ questions, better Crawler examples

packages/website/docs/migrating-from-legacy.mdx
**Summary**
This question has been asked multiple times, so I think it make sense to add it to the FAQ
=> docs(website): add more FAQ question

packages/website/docs/templates.mdx
**Summary**
The Docusaurus v2 template have changed, so the docs need an update
=> docs(template): update Docusaurus v2 template

packages/website/docs/migrating-from-legacy.mdx
- Adds a new question to let new users know that we are migrating active configs first.
- Add useful links
=> docs(migration): add useful links and new question

packages/website/docs/integrations.md
https://d.umijs.org/config#algolia
=> docs(integrations): add `dumi` to supported integrations

packages/website/src/components/ApplyForm.js
The infra now filters duplicate pending applications, this PR updates the `apply` form of the doc to reflect the message after applying.
Submit the same application multiple times from the Netlify preview :D
=> docs(apply): inform duplicate application

packages/website/docs/DocSearch-v3.mdx
=> docs: fix typo

packages/website/docs/record-extractor.md
=> docs: fix typo in record-extractor.md

packages/website/docs/api.mdx
Fixes https://github.com/algolia/docsearch/issues/1493
=> docs: remove duplicate links in `API` toc

packages/website/docs/DocSearch-program.md, packages/website/docs/crawler.mdx, packages/website/src/components/ApplyForm.js
Update the docs to make the support policy clearer to users.
=> docs: clearer support policy

packages/website/docs/DocSearch-v3.mdx
This will fix a typo in the documentation from  package manger to  package manager.
=> docs: fix typo in documentation

packages/website/docs/record-extractor.md, packages/website/src/components/Home.js
ticket: https://algolia.atlassian.net/browse/CRAW-2499
this PR fixes the documentation for `pageRank`
=> docs: fix `pageRank` type

packages/website/src/components/ApplyForm.js
Makes the "Repository URL" field optional on the form.
=> chore(apply): make repo URL optional

packages/website/src/css/custom.css
| Before | After |
|--------|--------|
| ![before](https://github.com/algolia/docsearch/assets/1145967/7c9be6d8-730a-4b97-bea8-009e0a839c58) | ![after](https://github.com/algolia/docsearch/assets/1145967/3ae73e2f-6aa2-4c53-b5f9-dc54da3be04b) |
=> fix(docs): sidebar logo size

packages/docsearch-css/build-css.js
as requested by @XhmikosR in https://github.com/algolia/docsearch/issues/2006
- adds a `style.scss` file to the `dist` folder
=> feat: add additional scss output

packages/website/src/css/custom.css
Roger X pointed out an issue with the site on mobile, a few people verified it was an issue, at least with chrome devtools, this change seems to fix the horizontal scrolling issue seen on mobile. Making the change in production to verify.
=> Fix: updating logo placement for mobile

packages/website/src/components/showcase-projects.json
I've followed up with each of these contacts but for now they're not using Algolia. Let's remove them.
=> fix(logos): removed logos no longer using algolia

packages/website/src/components/showcase-projects.json
=> fix(logos): they will not be fixing the search

packages/website/docs/v4/askai-api.mdx, packages/website/docs/v4/askai-markdown-indexing.mdx, packages/website/docs/v4/askai-prompts.mdx, packages/website/sidebars.js
This PR adds comprehensive documentation for enhancing AskAI accuracy through markdown indexing and provides a complete API reference for custom integrations.
- **`askai-markdown-indexing.mdx`** - Complete guide for improving answer quality with markdown-optimized indexes
- **`askai-api.mdx`** - Full API reference for custom Ask AI integrations
- **`docsearch.mdx`** - Added object format examples for `askAi` parameter alongside string format
- **`askai-prompts.mdx`** - Added proper summary and removed redundant content
- Step-by-step Crawler configuration for markdown content optimization
- Integration examples for Docusaurus, VitePress, Astro/Starlight, and generic setups
- Facet extraction patterns for multi-language and versioned documentation
- Both DocSearch and custom API …
=> feat(docs): api documentation and better examples

packages/docsearch-react/src/utils/storage.ts
This PR adds fallbacks to localstorage retrieve functions.
it will help capture poisoned data and wrongly structured localstorage items.
Fixes: https://github.com/algolia/docsearch/issues/2694
=> fix: localstorage error handling

packages/docsearch-css/src/modal.css
- Add display: flex to modal container for proper flex behavior  
- Change footer position from absolute to initial to fix layout issues
Fixes #2724
=> fix: modal layout issues with footer positioning
